version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.1.15
    - 6.1.20
    - 6.1.21
    - 6.2.2
    - 6.2.7
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.15
    - 6.2.2
    - 6.2.7
  - dependency-name: copy-webpack-plugin
    versions:
    - 8.1.0
  - dependency-name: "@types/chrome"
    versions:
    - 0.0.133
    - 0.0.134
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.13.10
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/cli"
    versions:
    - 7.13.0
    - 7.13.10
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.9
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.17
    - 6.1.20
  - dependency-name: "@storybook/preact"
    versions:
    - 6.1.15
    - 6.1.20
  - dependency-name: webpack
    versions:
    - 5.23.0
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
  - dependency-name: core-js
    versions:
    - 3.8.3
